name: weekly episode deployment

on:
    schedule:
        - cron: '30 12 * * 3'

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: satak/webrequest-action@master
              with:
                  url: https://api.vercel.com/v1/integrations/deploy/prj_Le3uQY4UbAhIL3mNIdOeH9FGidc4/kJs55mcDRI
                  method: POST
