name: Deploying Action

on:
    schedule:
        - cron: '59 23 * * *'

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: satak/webrequest-action@master
              with:
                  url: https://api.vercel.com/v1/integrations/deploy/prj_Le3uQY4UbAhIL3mNIdOeH9FGidc4/kJs55mcDRI
                  method: POST
